<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260811092425 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, province VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, is_primary BOOLEAN DEFAULT NULL, update_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, coordinates POINT, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_ADDRESS ON address (address_line1, city, province)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, telephone VARCHAR(30) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, vat_number VARCHAR(11) NOT NULL, invoice_note VARCHAR(255) DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, pec VARCHAR(100) DEFAULT NULL, sdi VARCHAR(7) DEFAULT NULL, bank_charge NUMERIC(5, 2) DEFAULT NULL, address_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09F5B7AF75 ON customer (address_id)');
        $this->addSql('CREATE TABLE driver_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category VARCHAR(30) NOT NULL, note VARCHAR(255) DEFAULT NULL, driver_id INT NOT NULL, vehicle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9DF4FACBC3423909 ON driver_log (driver_id)');
        $this->addSql('CREATE INDEX IDX_9DF4FACB545317D1 ON driver_log (vehicle_id)');
        $this->addSql('CREATE TABLE media_upload (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, update_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, mission_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ABC47CC1BE6CAE90 ON media_upload (mission_id)');
        $this->addSql('CREATE TABLE mission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ddt_reference VARCHAR(30) DEFAULT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pickup_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivered_before_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivery_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT DEFAULT NULL, weight INT NOT NULL, distance INT NOT NULL, price INT NOT NULL, status VARCHAR(50) NOT NULL, picked BOOLEAN NOT NULL, delivered BOOLEAN NOT NULL, express BOOLEAN NOT NULL, area NUMERIC(4, 1) NOT NULL, pickup_place_id INT NOT NULL, delivery_place_id INT NOT NULL, picking_vehicle_id INT DEFAULT NULL, delivering_vehicle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9067F23CA5AE5F4A ON mission (pickup_place_id)');
        $this->addSql('CREATE INDEX IDX_9067F23C6CC74375 ON mission (delivery_place_id)');
        $this->addSql('CREATE INDEX IDX_9067F23CE6A827FB ON mission (picking_vehicle_id)');
        $this->addSql('CREATE INDEX IDX_9067F23C585EE46F ON mission (delivering_vehicle_id)');
        $this->addSql('CREATE TABLE package (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, length INT NOT NULL, width INT NOT NULL, height INT NOT NULL, weight INT NOT NULL, aspect VARCHAR(50) DEFAULT NULL, quantity INT NOT NULL, mission_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DE686795BE6CAE90 ON package (mission_id)');
        $this->addSql('CREATE TABLE picture_upload (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, update_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, mission_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8659500FBE6CAE90 ON picture_upload (mission_id)');
        $this->addSql('CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, note VARCHAR(255) DEFAULT NULL, address_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_741D53CDF5B7AF75 ON place (address_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_PLACE_NAME ON place (name)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSONB NOT NULL, password VARCHAR(255) NOT NULL, fired_at DATE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plate VARCHAR(7) NOT NULL, length INT NOT NULL, width INT NOT NULL, height INT NOT NULL, weight_range INT NOT NULL, color VARCHAR(30) DEFAULT NULL, purchase_at DATE NOT NULL, next_tax_at DATE NOT NULL, next_inspection_at DATE NOT NULL, next_tachograph_at DATE DEFAULT NULL, is_available BOOLEAN NOT NULL, model VARCHAR(30) NOT NULL, note VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE driver_log ADD CONSTRAINT FK_9DF4FACBC3423909 FOREIGN KEY (driver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE driver_log ADD CONSTRAINT FK_9DF4FACB545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE media_upload ADD CONSTRAINT FK_ABC47CC1BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id)');
        $this->addSql('ALTER TABLE mission ADD CONSTRAINT FK_9067F23CA5AE5F4A FOREIGN KEY (pickup_place_id) REFERENCES place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mission ADD CONSTRAINT FK_9067F23C6CC74375 FOREIGN KEY (delivery_place_id) REFERENCES place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mission ADD CONSTRAINT FK_9067F23CE6A827FB FOREIGN KEY (picking_vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE mission ADD CONSTRAINT FK_9067F23C585EE46F FOREIGN KEY (delivering_vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE686795BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id)');
        $this->addSql('ALTER TABLE picture_upload ADD CONSTRAINT FK_8659500FBE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id)');
        $this->addSql('ALTER TABLE place ADD CONSTRAINT FK_741D53CDF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09F5B7AF75');
        $this->addSql('ALTER TABLE driver_log DROP CONSTRAINT FK_9DF4FACBC3423909');
        $this->addSql('ALTER TABLE driver_log DROP CONSTRAINT FK_9DF4FACB545317D1');
        $this->addSql('ALTER TABLE media_upload DROP CONSTRAINT FK_ABC47CC1BE6CAE90');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23CA5AE5F4A');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23C6CC74375');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23CE6A827FB');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23C585EE46F');
        $this->addSql('ALTER TABLE package DROP CONSTRAINT FK_DE686795BE6CAE90');
        $this->addSql('ALTER TABLE picture_upload DROP CONSTRAINT FK_8659500FBE6CAE90');
        $this->addSql('ALTER TABLE place DROP CONSTRAINT FK_741D53CDF5B7AF75');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE driver_log');
        $this->addSql('DROP TABLE media_upload');
        $this->addSql('DROP TABLE mission');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE picture_upload');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vehicle');
    }
}
